// Generated by hand from android/google-services.json
// Run `flutterfire configure` to regenerate if iOS support is added.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web is not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
            'iOS is not configured — add GoogleService-Info.plist and regenerate.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp88mcXXsfp2uNU_M_1eAUKGq9d-J7pVc',
    appId: '1:623371541775:android:2788dd1ad8daa33465727a',
    messagingSenderId: '623371541775',
    projectId: 'aarambd-6e757',
    storageBucket: 'aarambd-6e757.firebasestorage.app',
  );
}
